"""Initialize this checkout for local development (`./cli.sh :init`)."""

from __future__ import annotations

import argparse
import shutil
import stat
import subprocess
from pathlib import Path


CURRENT_HOOK_MARKER = "plane init hook"
GENERATED_HOOK_MARKERS = (
    CURRENT_HOOK_MARKER,
    "plane bootstrap hook",
)

# Installed hook name -> repo-relative template that holds its body.
HOOK_TEMPLATES = {
    "pre-commit": "scripts/resources/templates/hooks/precommit",
    "commit-msg": "scripts/resources/templates/hooks/commitmsg",
}

REQUIRED_TOOLS = (
    "git",
    "python3",
    "cargo",
    "uv",
    "sh",
    "bash",
    "sed",
    "grep",
)

REQUIRED_PATHS = (
    "Cargo.toml",
    "Cargo.lock",
    "cli.sh",
    "cli.ps1",
    "manage.sh",
    "manage.ps1",
    ".github/workflows/guard.yml",
    ".github/scripts/release/r2/publish.sh",
    ".github/scripts/release/smoke/smoke.sh",
    ".github/scripts/release/smoke/smoke.ps1",
    "scripts/pyproject.toml",
    "scripts/uv.lock",
    "scripts/cli/release.py",
    "scripts/cli/init.py",
    "scripts/resources/templates/hooks/precommit",
    "scripts/resources/templates/hooks/commitmsg",
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="./cli.sh :init", description=__doc__)
    parser.add_argument(
        "--force",
        action="store_true",
        help="replace existing non-init hooks after backing them up first",
    )
    args = parser.parse_args(argv)

    root = repo_root()
    print(f"==> repository: {root}")
    check_required_tools()
    check_required_paths(root)
    install_hooks(root, force=args.force)
    print("ok: development environment ready")
    return 0


def repo_root() -> Path:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except (FileNotFoundError, subprocess.CalledProcessError) as error:
        raise SystemExit("not inside a git checkout, or git is not available") from error
    return Path(result.stdout.strip())


def check_required_tools() -> None:
    print("==> checking required tools")
    missing = [tool for tool in REQUIRED_TOOLS if shutil.which(tool) is None]
    if missing:
        raise SystemExit("missing required tool(s): " + ", ".join(missing))
    print("ok: " + ", ".join(REQUIRED_TOOLS))


def check_required_paths(root: Path) -> None:
    print("==> checking repository entrypoints")
    missing = [path for path in REQUIRED_PATHS if not (root / path).is_file()]
    if missing:
        raise SystemExit("missing required path(s): " + ", ".join(missing))
    print("ok: " + ", ".join(REQUIRED_PATHS))


def install_hooks(root: Path, *, force: bool) -> None:
    print("==> installing git hooks")
    hooks_dir = git_path(root, "hooks")
    hooks_dir.mkdir(parents=True, exist_ok=True)
    for hook_name, template_rel in HOOK_TEMPLATES.items():
        content = (root / template_rel).read_text(encoding="utf-8")
        install_hook(root, hooks_dir / hook_name, content, force=force)


def git_path(root: Path, suffix: str) -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--git-path", suffix],
        cwd=root,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    path = Path(result.stdout.strip())
    if path.is_absolute():
        return path
    return root / path


def install_hook(root: Path, path: Path, content: str, *, force: bool) -> None:
    if path.exists() and not is_generated_hook(path):
        if not force:
            raise SystemExit(
                f"{display_path(root, path)} already exists and was not generated by "
                "./cli.sh :init; rerun with --force to back it up and replace it"
            )
        backup = next_backup_path(path)
        path.replace(backup)
        print(f"backed up existing hook to {display_path(root, backup)}")

    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"installed {display_path(root, path)}")


def is_generated_hook(path: Path) -> bool:
    text = path.read_text(encoding="utf-8", errors="replace")
    return any(marker in text for marker in GENERATED_HOOK_MARKERS)


def next_backup_path(path: Path) -> Path:
    backup = path.with_name(f"{path.name}.bak")
    if not backup.exists():
        return backup

    for index in range(1, 1000):
        candidate = path.with_name(f"{path.name}.bak.{index}")
        if not candidate.exists():
            return candidate

    raise SystemExit(f"too many existing hook backups for {path}")


def display_path(root: Path, path: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


if __name__ == "__main__":
    raise SystemExit(main())
