#!/usr/bin/env python3
"""Initialize this checkout for local development."""

from __future__ import annotations

import argparse
import shutil
import stat
import subprocess
import sys
from pathlib import Path


CURRENT_HOOK_MARKER = "plane init hook"
GENERATED_HOOK_MARKERS = (
    CURRENT_HOOK_MARKER,
    "plane bootstrap hook",
)

REQUIRED_TOOLS = (
    "git",
    "python3",
    "cargo",
    "uv",
    "sh",
    "bash",
    "sed",
    "grep",
)

REQUIRED_PATHS = (
    "Cargo.toml",
    "Cargo.lock",
    "cli.sh",
    "cli.ps1",
    "manage.sh",
    "manage.ps1",
    ".github/workflows/guard.yml",
    ".github/scripts/release/r2/publish.sh",
    ".github/scripts/release/smoke/smoke.sh",
    ".github/scripts/release/smoke/smoke.ps1",
    "scripts/pyproject.toml",
    "scripts/uv.lock",
    "scripts/cli/land.py",
    "scripts/cli/release.py",
    "scripts/init.py",
)

PRE_COMMIT_HOOK = f"""#!/usr/bin/env sh
# {CURRENT_HOOK_MARKER}: generated by scripts/init.py
set -eu
root=$(git rev-parse --show-toplevel)
cd "$root"

echo "==> cargo fmt"
cargo fmt --all --check

echo "==> cargo check"
cargo check --locked --workspace

echo "==> plane help smoke"
cargo run --locked -p plane-cli -- help

echo "==> shell syntax"
sh -n cli.sh
sh -n manage.sh
bash -n .github/scripts/release/r2/publish.sh
sh -n .github/scripts/release/smoke/smoke.sh

echo "==> python syntax"
python3 -m py_compile scripts/init.py
python3 -m py_compile scripts/cli/land.py
python3 -m py_compile scripts/cli/release.py
python3 -m py_compile scripts/lib/utils/cli.py

if command -v pwsh >/dev/null 2>&1; then
  echo "==> PowerShell syntax"
  pwsh -NoProfile -NonInteractive -Command \\
    '
$ErrorActionPreference = "Stop"
foreach ($path in @("./cli.ps1", "./manage.ps1", "./.github/scripts/release/smoke/smoke.ps1")) {{
  [scriptblock]::Create((Get-Content -Raw $path)) | Out-Null
}}
'
else
  echo "==> PowerShell syntax"
  echo "skip: pwsh not found"
fi
"""

COMMIT_MSG_HOOK = f"""#!/usr/bin/env sh
# {CURRENT_HOOK_MARKER}: generated by scripts/init.py
set -eu

if [ "$#" -ne 1 ] || [ ! -f "$1" ]; then
  echo "commit message file not found" >&2
  exit 1
fi

subject=$(sed -n '
/^[[:space:]]*#/d
/[^[:space:]]/ {{
  s/^[[:space:]]*//
  s/[[:space:]]*$//
  p
  q
}}
' "$1")

if [ -z "$subject" ]; then
  echo "commit subject is empty" >&2
  exit 1
fi

case "$subject" in
  "Merge "*|"Revert "*|"fixup!"*|"squash!"*)
    exit 0
    ;;
esac

if ! printf '%s\\n' "$subject" | grep -Eq '^[a-z][a-z0-9-]*(/[a-z0-9-]+)*: [^[:space:]].*'; then
  echo "commit subject must look like '<area>: <imperative summary>'" >&2
  echo "actual: $subject" >&2
  exit 1
fi

if [ "${{#subject}}" -gt 72 ]; then
  echo "warning: commit subject is ${{#subject}} chars; prefer <= 72" >&2
fi
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--force",
        action="store_true",
        help="replace existing non-init hooks after creating a numbered .bak copy",
    )
    args = parser.parse_args()

    root = repo_root()
    print(f"repository: {root}")
    check_required_tools()
    check_required_paths(root)
    install_hooks(root, force=args.force)
    print("development environment ready")
    return 0


def repo_root() -> Path:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except (FileNotFoundError, subprocess.CalledProcessError) as error:
        raise SystemExit("not inside a git checkout, or git is not available") from error
    return Path(result.stdout.strip())


def check_required_tools() -> None:
    print("==> checking required tools")
    missing = [tool for tool in REQUIRED_TOOLS if shutil.which(tool) is None]
    if missing:
        raise SystemExit("missing required tool(s): " + ", ".join(missing))
    print("ok: " + ", ".join(REQUIRED_TOOLS))


def check_required_paths(root: Path) -> None:
    print("==> checking repository entrypoints")
    missing = [path for path in REQUIRED_PATHS if not (root / path).is_file()]
    if missing:
        raise SystemExit("missing required path(s): " + ", ".join(missing))
    print("ok: " + ", ".join(REQUIRED_PATHS))


def install_hooks(root: Path, *, force: bool) -> None:
    print("==> installing git hooks")
    hooks_dir = git_path(root, "hooks")
    hooks_dir.mkdir(parents=True, exist_ok=True)
    install_hook(root, hooks_dir / "pre-commit", PRE_COMMIT_HOOK, force=force)
    install_hook(root, hooks_dir / "commit-msg", COMMIT_MSG_HOOK, force=force)


def git_path(root: Path, suffix: str) -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--git-path", suffix],
        cwd=root,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    path = Path(result.stdout.strip())
    if path.is_absolute():
        return path
    return root / path


def install_hook(root: Path, path: Path, content: str, *, force: bool) -> None:
    if path.exists() and not is_generated_hook(path):
        if not force:
            raise SystemExit(
                f"{path} already exists and was not generated by scripts/init.py; "
                "rerun with --force to back it up and replace it"
            )
        backup = next_backup_path(path)
        path.replace(backup)
        print(f"backed up existing hook to {display_path(root, backup)}")

    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"installed {display_path(root, path)}")


def is_generated_hook(path: Path) -> bool:
    text = path.read_text(encoding="utf-8", errors="replace")
    return any(marker in text for marker in GENERATED_HOOK_MARKERS)


def next_backup_path(path: Path) -> Path:
    backup = path.with_name(f"{path.name}.bak")
    if not backup.exists():
        return backup

    for index in range(1, 1000):
        candidate = path.with_name(f"{path.name}.bak.{index}")
        if not candidate.exists():
            return candidate

    raise SystemExit(f"too many existing hook backups for {path}")


def display_path(root: Path, path: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


if __name__ == "__main__":
    raise SystemExit(main())
